# Description:
- In this section I will demo the real tensorflow code with output from the slide http://web.stanford.edu/class/cs20si/lectures/slides_02.pdf. 
- I also show Keras equivalent API as well as sometimes so how to combine them when keras equivalent API does not have.


In [ ]:
import tensorflow as tf
from keras import backend as K


def eval(x):
    with tf.Session() as sess:
        return sess.run(x)

In [44]:
"""Visualize it with TensorBoard"""

# test TF
a = tf.constant(2, name="a")
b = tf.constant(3, name="b")
x = tf.add(a, b, name="add")
writer = tf.summary.FileWriter("./graphs", sess.graph)
print eval(x)

# test Keras
a = K.variable(2, name='a')
b = K.variable(3, name='b')
x = a + b
print K.eval(x)

5
5.0


In [45]:
"""tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False)"""

# test TF
a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
x = tf.add(a, b, name='add')
y = tf.multiply(a, b, name='mul')

x_o, y_o = eval([x, y])

print x_o
print y_o


# test Keras
a = K.variable([2, 2], name='a')
b = K.variable([[0, 1], [2, 3]], name='b')
x = a + b
y = a * b
print K.eval(x)
print K.eval(y)

[[2 3]
 [4 5]]
[[0 2]
 [4 6]]
[[ 2.  3.]
 [ 4.  5.]]
[[ 0.  2.]
 [ 4.  6.]]


In [50]:
"""tf.zeros(shape, dtype=tf.float32, name=None)
creates a tensor of shape and all elements will be zeros (when ran in session)
"""

x = tf.zeros([2, 3], tf.int32)
print eval(x)

# keras

x = K.zeros([2, 3], dtype='float32')
print K.eval(x)

[[0 0 0]
 [0 0 0]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [51]:
"""tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)
creates a tensor of shape and type (unless type is specified) as the input_tensor but all elements are zeros.

tf.ones(shape, dtype=tf.float32, name=None)
tf.ones_like(input_tensor, dtype=None, name=None, optimize=True)
"""

input_tensor = [[0, 1], [2, 3], [4, 5]]
x = tf.zeros_like(input_tensor)

print eval(x)

# Keras
x = K.zeros_like(input_tensor)
print K.eval(x)

[[0 0]
 [0 0]
 [0 0]]
[[0 0]
 [0 0]
 [0 0]]


In [55]:
"""tf.fill(dims, value, name=None) 
creates a tensor filled with a scalar value.

"""

x = tf.fill([2, 3], 8)

print eval(x)

# Keras
x = 8 * K.ones((2,3), dtype='float32')
print K.eval(x)

[[8 8 8]
 [8 8 8]]
[[ 8.  8.  8.]
 [ 8.  8.  8.]]


In [75]:
"""Constant as sequence
tf.linspace(start, stop, num, name=None) # slightly different from np.linspace
tf.range(start, limit=None, delta=1, dtype=None, name='range')
"""

# Test TF
    
x = tf.linspace(10.0, 13.0, 4)
print eval(x)

y = tf.range(3, 13, 3)
print eval(y)

# Test Keras
x1 = K.variable(np.linspace(10.0, 13.0, 4))
print K.eval(x)

y1 = K.arange(5)
print K.eval(y)

# mix keras with tf easily
z = x + x1
print K.eval(z)

[ 10.  11.  12.  13.]
[ 3  6  9 12]


[ 10.  11.  12.  13.]


[ 3  6  9 12]


[ 20.  22.  24.  26.]


In [76]:
"""
Randomly Generated Constants
tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None) # Keras doesn't have
tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)
tf.random_shuffle(value, seed=None, name=None) # Keras doesn't have
tf.random_crop(value, size, seed=None, name=None) # Keras doesn't have
tf.multinomial(logits, num_samples, seed=None, name=None) # Keras doesn't have
tf.random_gamma(shape, alpha, beta=None, dtype=tf.float32, seed=None, name=None) # Keras doesn't have
tf.set_random_seed(seed) # Keras doesn't have
"""

x1 = tf.random_normal((2,3))
print eval(x1)
x2 = tf.random_uniform((2,3))
print eval(x2)

x1 = K.random_normal((2,3))
print eval(x1)
x2 = K.random_uniform((2,3))
print eval(x2)

[[ 0.16967137  0.86939454 -0.16643368]
 [ 0.3247923  -0.27238673 -1.15250576]]
[[ 0.08613408  0.70415497  0.11248028]
 [ 0.6262598   0.74641204  0.6851263 ]]


[[ 0.9811095  -0.07128934 -0.42899767]
 [ 0.01736452  1.45493162 -0.62472349]]


[[ 0.64149487  0.45819783  0.02861166]
 [ 0.81258011  0.54619575  0.16919816]]