# TensorFlow Ops:

In this section, we will demo the second tutorial http://web.stanford.edu/class/cs20si/lectures/slides_02.pdf 

We also include the equivalent Keras code.


In [10]:
%run global_variables.py

In [11]:
"""Visualize it with TensorBoard"""

# test TF
a = tf.constant(2, name="a")
b = tf.constant(3, name="b")
x = tf.add(a, b, name="add")
writer = tf.summary.FileWriter("./graphs", sess.graph)
print eval(x)

# test Keras
a = K.variable(2, name='a')
b = K.variable(3, name='b')
x = a + b
print K.eval(x)

5
5.0


In [45]:
"""tf.constant(value, dtype=None, shape=None, name='Const', verify_shape=False)"""

# test TF
a = tf.constant([2, 2], name='a')
b = tf.constant([[0, 1], [2, 3]], name='b')
x = tf.add(a, b, name='add')
y = tf.multiply(a, b, name='mul')

x_o, y_o = eval([x, y])

print x_o
print y_o


# test Keras
a = K.variable([2, 2], name='a')
b = K.variable([[0, 1], [2, 3]], name='b')
x = a + b
y = a * b
print K.eval(x)
print K.eval(y)

[[2 3]
 [4 5]]
[[0 2]
 [4 6]]
[[ 2.  3.]
 [ 4.  5.]]
[[ 0.  2.]
 [ 4.  6.]]


In [50]:
"""tf.zeros(shape, dtype=tf.float32, name=None)
creates a tensor of shape and all elements will be zeros (when ran in session)
"""

x = tf.zeros([2, 3], tf.int32)
print eval(x)

# keras

x = K.zeros([2, 3], dtype='float32')
print K.eval(x)

[[0 0 0]
 [0 0 0]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [51]:
"""tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)
creates a tensor of shape and type (unless type is specified) as the input_tensor but all elements are zeros.

tf.ones(shape, dtype=tf.float32, name=None)
tf.ones_like(input_tensor, dtype=None, name=None, optimize=True)
"""

input_tensor = [[0, 1], [2, 3], [4, 5]]
x = tf.zeros_like(input_tensor)

print eval(x)

# Keras
x = K.zeros_like(input_tensor)
print K.eval(x)

[[0 0]
 [0 0]
 [0 0]]
[[0 0]
 [0 0]
 [0 0]]


In [3]:
"""tf.fill(dims, value, name=None) 
creates a tensor filled with a scalar value.

"""

x = tf.fill([2, 3], 8)

print eval(x)

# Keras
x = 8 * K.ones((2,3), dtype='float32')
print K.eval(x)

[[8 8 8]
 [8 8 8]]
[[ 8.  8.  8.]
 [ 8.  8.  8.]]


In [75]:
"""Constant as sequence
tf.linspace(start, stop, num, name=None) # slightly different from np.linspace
tf.range(start, limit=None, delta=1, dtype=None, name='range')
"""

# Test TF
    
x = tf.linspace(10.0, 13.0, 4)
print eval(x)

y = tf.range(3, 13, 3)
print eval(y)

# Test Keras
x1 = K.variable(np.linspace(10.0, 13.0, 4))
print K.eval(x)

y1 = K.arange(5)
print K.eval(y)

# mix keras with tf easily
z = x + x1
print K.eval(z)

[ 10.  11.  12.  13.]
[ 3  6  9 12]
[ 10.  11.  12.  13.]
[ 3  6  9 12]
[ 20.  22.  24.  26.]


In [80]:
"""
Randomly Generated Constants
tf.random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
tf.truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None) # Keras doesn't have
tf.random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)
tf.random_shuffle(value, seed=None, name=None) # Keras doesn't have
tf.random_crop(value, size, seed=None, name=None) # Keras doesn't have
tf.multinomial(logits, num_samples, seed=None, name=None) # Keras doesn't have
tf.random_gamma(shape, alpha, beta=None, dtype=tf.float32, seed=None, name=None) # Keras doesn't have
tf.set_random_seed(seed) # Keras doesn't have
"""

x1 = tf.random_normal((2,3))
print eval(x1)
x2 = tf.random_uniform((2,3))
print eval(x2)

x1 = K.random_normal((2,3))
print eval(x1)
x2 = K.random_uniform((2,3))
print eval(x2)

[[ 0.97839284 -0.07782374 -1.08000886]
 [-1.50186384 -0.059723    0.22159982]]
[[ 0.72305012  0.72165501  0.99812424]
 [ 0.718279    0.93321419  0.40319037]]
[[  1.45784068e+00  -2.30176046e-01  -7.34288692e-01]
 [ -4.68101352e-01   2.67075688e-01   4.76315676e-04]]
[[ 0.21128476  0.17148471  0.35090828]
 [ 0.34566164  0.81865156  0.08582115]]


In [9]:
"""TensorFlow Operations"""

a = tf.constant([3, 6])
b = tf.constant([2, 2])
x1 = tf.add(a, b)  # >> [5 8]
x2 = tf.add_n([a, b, b])  # >> [7 10]. Equivalent to a + b + b
# x3 = tf.multiply(a, b)  # >> [6 12] because mul is element wise
# x4 = tf.matmul(a, b)  # >> ValueError
x5 = tf.matmul(tf.reshape(a, [1, 2]), tf.reshape(b, [2, 1]))  # >> [[18]]
x6 = tf.div(a, b)  # >> [1 3]
x7 = tf.mod(a, b)  # >> [1 0]
print eval(x2)

# Keras does not have operations like TensorFlow, so we should use TensorFlow operation instead
a = K.variable([3, 6])
b = K.variable([2, 2])
x1 = tf.add(a, b)
x2 = tf.add_n([a, b, b])
print K.eval(x2).astype('int32')

[ 7 10]
[ 7 10]


In [17]:
"""TensorFlow Data Types
TensorFlow takes Python natives types: boolean, numeric (int, float), strings
"""

# 0-d tensor, or "scalar" 
t_0 = 19
print eval(tf.zeros_like(t_0)) # ==> 0
print eval(tf.ones_like(t_0)) # ==> 1

# 1-d tensor, or "vector"
t_1 = ['apple', 'peach', 'banana']
print eval(tf.zeros_like(t_1)) # ==> ???????

# 2x2 tensor, or "matrix"
t_2 = [[True, False, False],
 [False, False, True],
 [False, True, False]]
print eval(tf.zeros_like(t_2)) # ==> 2x2 tensor, all elements are False
print eval(tf.ones_like(t_2)) # ==> 2x2 tensor, all elements are True

0
1
['' '' '']
[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [26]:
"""TF vs NP Data Types
- Do not use Python native types for tensors because TensorFlow has to infer Python
type
- Beware when using NumPy arrays because NumPy and TensorFlow might become not so compatible in the future!
"""
import numpy as np
# TensorFlow integrates seamlessly with NumPy
tf.int32 == np.int32 # True
# Can pass numpy types to TensorFlow ops
eval(tf.ones([2, 2], np.float32)) # ⇒ [[1.0 1.0], [1.0 1.0]]

array([[ 1.,  1.],
       [ 1.,  1.]], dtype=float32)

In [30]:
"""Printout the Graph def

Only use constants for primitive types.
Use variables or readers for more data that
requires more memory
"""
tf.reset_default_graph()

my_const = tf.constant([1.0, 2.0], name="my_const")

with tf.Session() as sess:
    print sess.graph.as_graph_def()

node {
  name: "my_const"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\000\000\200?\000\000\000@"
      }
    }
  }
}
versions {
  producer: 21
}



In [42]:
"""How about variables?"""

# create variable a with scalar value
a = tf.Variable(2, name="scalar")
# create variable b as a vector
b = tf.Variable([2, 3], name="vector")
# create variable c as a 2x2 matrix
c = tf.Variable([[0, 1], [2, 3]], name="matrix")
# create variable W as 784 x 10 tensor, filled with zeros
W = tf.Variable(tf.zeros([784,10]))

# print eval(a) # will have error, will have to initialize in another way

"""You have to initialize your variables"""
# The easiest way is initializing all variables at once:
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)

# Initialize only a subset of variables:
init_ab = tf.variables_initializer([a, b], name="init_ab")
with tf.Session() as sess:
    sess.run(init_ab)
    print a.eval()
    
# Initialize a single variable
W = tf.Variable(tf.zeros([784,10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print W.eval()
    
# Keras automatically initialize all variables when K.eval(), we don't care much about this

2
[[ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]]


In [7]:
"""tf.Variable.assign()"""

W = tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print W.eval()  # >> 10

# --------
"""W.assign(100) doesn’t assign the value 100
to W. It creates an assign op, and that op
needs to be run to take effect."""

W = tf.Variable(10)
assign_op = W.assign(100)
with tf.Session() as sess:
    # sess.run(W.initializer)  # You don’t need to initialize variable because assign_op does it for you
    sess.run(assign_op) 
    print W.eval()  # >> 100

# create a variable whose original value is 2
my_var = tf.Variable(2, name="my_var")
# assign a * 2 to a and call that op a_times_two
my_var_times_two = my_var.assign(2 * my_var)

with tf.Session() as sess:
    sess.run(my_var.initializer)
    print sess.run(my_var_times_two) # >> 4
    print sess.run(my_var_times_two) # >> 8
    print sess.run(my_var_times_two) # >> 16
    
# Keras

my_kvar = K.variable(2, name='my_kvar')
my_kvar_times_two = my_kvar.assign(2 * my_kvar)

print K.eval(my_kvar)
print K.eval(my_kvar_times_two)
print K.eval(my_kvar_times_two)

10
100
4
8
16
2.0
4.0
8.0


In [8]:
"""assign_add() and assign_sub()"""

my_var = tf.Variable(10)
with tf.Session() as sess:
    print sess.run(my_var.initializer)
    # increment by 10
    print sess.run(my_var.assign_add(10)) # >> 20
    # decrement by 2
    print sess.run(my_var.assign_sub(2)) # >> 18
    
# Keras
my_kvar = K.variable(10)
print K.eval(my_kvar)
print K.eval(my_kvar.assign_add(10))
print K.eval(my_kvar.assign_sub(2))

None
20
18
10.0
20.0
18.0


In [9]:
"""Each session maintains its own copy of variable"""

W = tf.Variable(10)
sess1 = tf.Session()
sess2 = tf.Session()
sess1.run(W.initializer)
sess2.run(W.initializer)
print sess1.run(W.assign_add(10)) # >> 20
print sess2.run(W.assign_sub(2)) # >> 8
print sess1.run(W.assign_add(100)) # >> 120
print sess2.run(W.assign_sub(50)) # >> -42
sess1.close()
sess2.close()

20
8
120
-42


In [26]:
"""Use a variable to initialize another variable"""

# W is a random 700 x 100 tensor
W = tf.Variable(tf.truncated_normal([700, 10]))
U = tf.Variable(2 * W.initialized_value())

print eval(U.initialized_value())

# Mix Keras and TF
print K.eval(U)

# Keras
W_k = K.variable(tf.truncated_normal([700, 10]))
U_k = K.variable(2 * W_k.initialized_value())

print K.eval(W_k)
print K.eval(U_k)

[[ 0.97359836  0.8813414   3.01833415 ...,  2.26067066  1.15427721
   2.91136003]
 [-1.2266953  -1.38249469  0.5946216  ...,  1.84884286  1.0035181
   2.70322084]
 [-0.97677541 -0.25401503  1.87833726 ...,  2.44167018  2.44995737
  -0.28475642]
 ..., 
 [ 1.62976933 -2.96452689  0.30112812 ...,  1.36951935  0.1850547
   2.46214271]
 [-1.26830709 -1.14958024 -0.04049495 ...,  0.91509944  0.687747
   0.41758695]
 [ 2.04626989  0.70260978 -0.50159144 ..., -0.36819997  3.71318197
  -2.47867203]]
[[ 0.33436131 -1.27145898  0.44782084 ..., -1.38956022  0.99035555
   1.25545251]
 [-2.62990093 -0.08680313 -0.0349321  ...,  1.15094924 -0.1765009
  -0.9430725 ]
 [ 0.15960066  1.31463027  2.21136832 ..., -0.92541623  1.2637248
  -1.21196127]
 ..., 
 [-0.25661144 -0.96694374 -2.522403   ..., -2.38207769 -3.5871284
  -0.78476524]
 [ 0.6510753   2.27234244  0.93697429 ..., -0.59740782 -3.04257941
  -0.63806444]
 [-0.44995219 -2.65151095  2.66072655 ...,  0.46368223 -3.05945683
  -1.69586933]]
[[ 0.66

In [31]:
"""Session vs InteractiveSession"""

sess = tf.InteractiveSession()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
# We can just use 'c.eval()' without specifying the context 'sess'
print(c.eval())
sess.close()

# Keras
a = K.variable(5.)
b = K.variable(6.)
c = a * b
print K.eval(c)

30.0


30.0

In [34]:
"""Placeholders
tf.placeholder(dtype, shape=None, name=None)"""

# create a placeholder of type float 32-bit, shape is a vector of 3 elements
a = tf.placeholder(tf.float32, shape=[3])
# create a constant of type float 32-bit, shape is a vector of 3 elements
b = tf.constant([5, 5, 5], tf.float32)
# use the placeholder as you would a constant or a variable
c = a + b # Short for tf.add(a, b)

with tf.Session() as sess:
    # print sess.run(c) # Error because a doesn’t have any value
    
    # feed [1, 2, 3] to placeholder a via the dict {a: [1, 2, 3]}
    # fetch value of c
    print sess.run(c, {a: [1, 2, 3]}) # the tensor a is the key, not the string ‘a’
    
    # or you can feed in this way:
    print sess.run(c, feed_dict={a: [1, 2, 3]})

[ 6.  7.  8.]
[ 6.  7.  8.]


In [5]:
"""Lazy Loading"""

# Normal loading:
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x, y) # you create the node for add node before executing the graph

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter('./my_graph/l2', sess.graph)
    for _ in range(10):
        print sess.run(z)
    writer.close()
    
# Lazy loading:
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter('./my_graph/l2', sess.graph)
    for _ in range(10):
        print sess.run(tf.add(x, y)) # someone decides to be clever to save one line of code
    writer.close()

# Keras
x = K.variable(10, name='x')
y = K.variable(20, name='y')

for _ in range(10):
    print K.eval(x + y)

30.0
30.0
30.0
30.0
30.0
30.0
30.0
30.0
30.0
30.0
